project:
  type: website
  render:
    - "*.qmd"
    - "!dataproc/"

website:
  title: "Sea Ice @ Alaska"

  sidebar:
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/polarwatch/alaska-seaice
        text: "PolarWatch Repository"
        target: _blank
      - icon: globe
        href: https://polarwatch.noaa.gov
        text: "PolarWatch Website"
        target: _blank

    contents:
      - href: index.qmd
        text: "Main"
      - href: arctic.qmd
        text: "Alaskan Arctic"
      - href: ebering.qmd
        text: "Eastern Bering"
      - href: nbering.qmd
        text: "Northern Bering"
      - href: sebering.qmd
        text: "Southeastern Bering"
      - href: methods.qmd
        text: "Data and Methods"
      - href: https://shinyfin.psmfc.org/ak-sst-mhw/      
        text: "ShinyFIN (SST)"
        target: _blank
      - href: https://polarwatch.noaa.gov
        text: "PolarWatch"
        target: _blank
        

format:
  html:
    grid:
      # sidebar-width: 200px
      body-width: 960px
    theme: flatly
    css: styles.css
    include-after-body: custom.js
    toc: true


exclude:
  - "scripts/"
  - "dataproc/"

editor: visual

