## Contributions and Citations


### Contributors

* Sun Hospital, PolarWatch Operations Manager at PolarWatch, NOAA CoastWatch, UCSC Fisheries Cooperative Program
* Elizabeth Siddon, NOAA Alaska Fisheries Science Center
* Ludovic Brucker, NOAA NESDIS Center for Satellite Applications & Research
* Matt Calahan, Alaska Fisheries Information Network 

### Citations

**Data**

NOAA/NSIDC. (n.d.). Climate Data Record of Passive Microwave Sea Ice Concentration, Version 4. DATA SET ID: G02202. https://doi.org/10.7265/EFMZ-2T65

Callahan, M. (2023/12/1). AKmarineareas: Management relevent spatial data for Alaska marine areas. Retrieved from https://github.com/MattCallahan-NOAA/AKmarineareas/



**Data Access/Visualization**

NOAA/CoastWatch PolarWatch. (n.d.). Data Access and Visualization of Climate Data Record of Passive Microwave Sea Ice Concentration, Version 2 and 4 DATA SET ID: (nsidcG02202v4nhmday
, nsidcG10016v2nhmday). Retrieved from https://polarwatch.noaa.gov/catalog/

**Statistics and Plots**

NOAA/CoastWatch PolarWatch. (n.d.). Sea ice extent time series for Alaska region. Retrieved from https://polarwatch.github.com/polarwatch/alaska-seaice  [github]()

**Software**

Hoyer, S., & Hamman, J. (n.d.). xarray: N-D labeled arrays and datasets in Python. Retrieved from http://xarray.pydata.org

Chamberlain, S. (n.d.). rerddap: General purpose client for ERDDAP servers. Retrieved from https://github.com/ropensci/rerddap

Quarto Authors (n.d). Quarto: An Open-Source Scientific and Technical Publishing System Built on Pandoc. Retrieved from https://github.com/quarto-dev/quarto-cli

Chart.js Downie N. et al. (2023). Chart.js (v4.4.1): Simple yet flexible JavaScript charting for designers & developers. Retrieved from https://www.chartjs.org/

:::{.callout-info}
to-do: add chartjs htmlwidget

:::

