---
title: "Sea Ice Extent Calculation"
format: 
  html:
    code-fold: true
---

The sea ice extent is derived from the sea ice concentration remote sensing data. 


### Data

**The NOAA/NSIDC Climate Data Record (CDR) Sea Ice Concentration data product**


The NOAA/NSIDC 25-km sea ice concentration data product provides 
daily and monthly datasets available in two versions: science quality (SQ)
and near real-time (NRT). The science quality dataset has been available since 1978.

Sea ice extent calculations primarily utilize the science quality 
version. However, to ensure the time series is as current as possible, 
near-real-time data are initially used. Once the science quality (SQ) 
data become available, they replace the near-real-time data in the calculations.


* [NOAA/NSIDC. (n.d.). Climate Data Record of Passive Microwave Sea Ice Concentration, Version 4](https://polarwatch.noaa.gov/catalog/ice-sq-nh-nsidc-cdr-v4/preview/?dataset=monthly&var=cdr_seaice_conc_monthly&time_min=2023-12-01T00:00:00Z&time_max=2023-12-01T00:00:00Z&proj=epsg3413&colorBar=KT_ice,,,0,1,)
* [NOAA/NSIDC. (n.d.). Climate Data Record of Near-Real-Time Passive Microwave Sea Ice Concentration, Version 2](https://polarwatch.noaa.gov/catalog/ice-nrt-nh-nsidc-cdr-v2/preview/?dataset=monthly&var=cdr_seaice_conc_monthly&time_min=2024-03-01T00:00:00Z&time_max=2024-03-01T00:00:00Z&proj=epsg3413&colorBar=KT_ice,,,0,1,)

### Sea Ice Extent Calculation

The sea ice extent is calculated as the total area, measured in square kilometers (km2), 
where each grid cell exhibits a sea ice concentration of 15% or more.

```{mermaid}
flowchart LR
  A("Get SQ Data") -->  B("Append NRT Data")
  B --> C("Subset Data for Region") 
  C --> D("Compute Sea Ice Extent")
```

| Action | Description |  
|--|:-----| 
| Get SQ Data      | Get the Monthly Science Quality Sea ice concentration data from 1985 to the latest data    |  
| Append NRT Data     | Get the monthly Near-Real Time sea ice concentration data to extend the time series to the latest data available   |   
| Subset Data for Region       | Subset the sea ice concentration data to only include the region of interest using shapefiles provided by AKFIN    |   
| Compute Sea Ice Extent       | Compute sea ice extent time series    |   

: Workflow to compute sea ice extent

### Sea Ice Extent Code 

The sea ice extent code used to compute statistics is available on Github.
Please check zenodo for citations.
