# Sea ice Extent in Alaska region

This website presents daily time series of sea ice extent and its anomaly within the management regions of Alaskan waters.

The website features sea ice extent data for three regions defined by the Ecosystem Management Regions: the Alaskan Arctic, Eastern Bering Sea, and the Northern Bering Sea (a subset of the Eastern Bering sea).

Sea ice extent for each region is calculated using sea ice concentration data available from NOAA PolarWatch and is updated automatically when the new data are available.

## Data

Sea ice concentration represents the fraction (between 0 and 1) of the grid cell covered by sea ice. This can be estimated using satellite microwave radiometers. To compute the sea ice extent baseline (i.e., the 30-year climatology), satellite Climate Data Record (CDR) sea ice concentration data from 1985 to 2015 were pulled from [PolarWatch](https://polarwatch.noaa.gov/catalog/ice-sq-nh-nsidc-cdr-v4/preview/?dataset=monthly&var=cdr_seaice_conc_monthly&time_min=2023-12-01T00:00:00Z&time_max=2023-12-01T00:00:00Z&proj=epsg3413&colorBar=KT_ice,,,0,1,). The sea ice extent values of the two most recent years were computed using the Near-real-time Sea Ice Concentration data.  

__Climate Data Record (CDR) of Passive Microwave Sea Ice Concentration__

This data set provides a CDR of sea ice concentration at 25 km resolution. Daily and monthly versions are available from 1978 to the most recent annual processing. The data are deemed of science quality. The product name is NOAA/NSIDC Climate Data Record of Passive Microwave Sea Ice Concentration, Version 4 (G02202), doi:10.7265/EFMZ-2T65.
[Link to Data](https://polarwatch.noaa.gov/catalog/ice-sq-nh-nsidc-cdr-v4/preview/?dataset=monthly&var=cdr_seaice_conc_monthly&time_min=2023-12-01T00:00:00Z&time_max=2023-12-01T00:00:00Z&proj=epsg3413&colorBar=KT_ice,,,0,1,)


__Near-real-time Sea Ice Concentration__

The NRT CDR of sea ice concentration at 25 km is updated daily and used while waiting for the annual processing of the science quality CDR described above. Daily and monthly versions are available. The product name is Near Real-Time NOAA/NSIDC Sea Ice Concentration Climate Data Record, Version 2 (G10016), doi:10.7265/TGAM-YV28.
[Link to Data](https://polarwatch.noaa.gov/catalog/ice-nrt-nh-nsidc-cdr-v2/preview/?dataset=monthly&var=cdr_seaice_conc_monthly&time_min=2024-09-01T00:00:00Z&time_max=2024-09-01T00:00:00Z&proj=epsg3413&colorBar=KT_ice,,,0,1,)

__Polar Stereographic Grid Cell Area__

This dataset includes grid cell area values for the 25-km polar stereographic grid used for the sea ice concentration data.
[Link to Data](https://polarwatch.noaa.gov/erddap/griddap/pstere_gridcell_N25k.html)

## Methods

Sea ice extent is calculated as the sum of the areas of each grid cell where the sea ice concentration meets or exceeds a specified threshold, indicating the presence of sea ice. Typically, that threshold is 0.15 (i.e. when the sea ice concentration estimated in that grid cell is 15% of greater, the area of the entire grid cell is used to calculate the sea ice extent). Alternatively, one can also calculate the sea ice area, in which case the grid cell area is multiplied by the sea ice concentration. Here, we work with sea ice extent.

### Sea ice extent

Let $sic_{ij}$ be the satellite estimated sea ice concentration (i.e., fraction) of the $ij^{th}$ grid cell covered by sea ice.

Sea ice extent of a ${region}$ is defined as follows:

$$
\text{Sea Ice Extent}_{\text{region, time}} = \sum_{i \in \text{xgrid}, j \in \text{ygrid}} seaice_{ij,\text{region, time}} \cdot \text{cellarea}_{ij, \text{region}}
$$

$$ 
\text {where} 
\ seaice_{ij, region, time} =
\begin{cases} 
1 & \text{if } sic_{ij,\text{region, time}} \geq 0.15, \\
0 & \text{otherwise.}
\end{cases}
$$

__Workflow of Data Processing and Computation:__

1.  __Data Import for Baseline__ Import Climate Data Record (CDR) sea ice concentration data from 1991 to 2020 within the specified regional boundaries to compute daily baseline. 

2. __Data Import for most recent years__ Import Near-Real-Time sea ice concentration data to the CDR time series.

3. __Data Cleaning__ Remove all flag values (non-sea ice concentration values) from the dataset.

4. __Data Conversion__ Convert sea ice concentration values from fractions to binary values using a threshold of 0.15 (0 indicates no ice, 1 indicates ice presence).

4. __Sea Ice Extent Calculation__ Sum the grid cell areas across all grids to obtain the total sea ice extent within the regional boundaries.


### Daily sea ice extent baseline

The daily sea ice extent baseline for a given region was computed using sea ice extent from 1991 to 2020 based on the NOAA's [recommendadtions](https://www.noaa.gov/explainers/understanding-climate-normals), and defined as follows:

$$
\text{Sea ice extent baseline}_{\text{region, day}} = Mean (\text{Sea ice extent}_{\text{region, day, year} \in [1985, 2015]})
$$ 

### Daily sea ice extent anomaly

The daily sea ice extent anomaly for a given region was computed using sea ice extent baseline:

$$
\text{Sea ice extent anomaly}_{\text{region, day, year}} = \text{Sea ice extent}_{\text{region, day, year}} - \text{Sea ice extent baseline}_{\text{region, day}} 
$$ 

### Annualized sea ice extent

The annualized sea ice extent for a given region was computed by averaging monthly sea ice extent values. 


$$
\text{Annualized sea ice extent}_{\text{region, year}} = \text{Mean} \left( \text{Sea ice extent}_{\text{region, date in [September (year-1), August (year)]}} \right)
$$


### Codes

The data processing and computation was performed using Python and the webpage generation and visualization were done using Quartot and R. 
The codes are available in `dataproc/` directory of the [github repository](https://github.com/polarwatch/alaska-seaice).


## Intended Use

The intended use of the data summaries, which include sea ice extent baselines and anomalies, is to compare the recent year's sea ice extent against the 30-year baseline of sea ice extent. It is important to note that no additional data cleaning has been performed beyond what is described here. Users are advised to conduct further evaluations of the data and analysis themselves.

## Contact us

For any questions, comments, or feedback, email us at polar.watch@noaa.gov or create a Github [Issue](https://github.com/polarwatch/alaska-seaice/issues/new).

## Contributors

* [PolarWatch Team](https://polarwatch.noaa.gov/about/contact/), NOAA CoastWatch, UCSC Fisheries Cooperative Program
* Elizabeth Siddon, NOAA Alaska Fisheries Science Center
* Ludovic Brucker, NOAA NESDIS Center for Satellite Applications & Research

## Acknowledgments
We thank Matt Calahan from the Alaska Fisheries Information Network (AKFIN) for his valuable insights, R package, and resources. We also appreciate Andy Teucher from OpenScapes for his contributions to the GitHub workflow. Their input was instrumental in the development of this work.

## References

**Data**

NOAA/NSIDC. (n.d.). Climate Data Record of Passive Microwave Sea Ice Concentration, Version 4, Arctic. DATA SET ID: G02202. https://doi.org/10.7265/EFMZ-2T65

NOAA/NSIDC. (n.d). Near-Real-Time Climate Data Record of Passive Microwave Sea Ice Concentration  Version 2, Arctic. DATA SET ID: G10016.https://doi.org/10.7265/TGAM-YV28

Callahan, M. (2023/12/1). AKmarineareas: Management relevant spatial data for Alaska marine areas. Retrieved from https://github.com/MattCallahan-NOAA/AKmarineareas/

**Data Access**

NOAA/CoastWatch PolarWatch. (n.d.). Data Access and Visualization of Climate Data Record of Passive Microwave Sea Ice Concentration, Version 2 and 4 DATA SET ID: (nsidcG02202v4nh1day
, nsidcG10016v2nh1day).  https://polarwatch.noaa.gov/catalog/

**Statistics and Plots**

NOAA/CoastWatch PolarWatch. (n.d.). Sea ice extent time series for Alaska region. 

**Software**

Hoyer, S., & Hamman, J. (n.d.). xarray: N-D labeled arrays and datasets in Python. Retrieved from http://xarray.pydata.org

Quarto Authors (n.d). Quarto: An Open-Source Scientific and Technical Publishing System Built on Pandoc. Retrieved from https://github.com/quarto-dev/quarto-cli

R Core Team (2020). R(version) [Statistical package] Retrieved from https://www.R-project.org/. 

Python Software Foundation. (2024). Python (3.10.14) [Computer software]. Retrieved from https://www.python.org.

