---
title: "Sea Ice in Alaska"
---

### What is Sea Ice?

Sea ice is seawater that has frozen and floats in the ocean, forming exclusively within the ocean itself. Unlike sea ice, icebergs, glaciers, and ice shelves originate on land before breaking off and floating in the ocean. In the Arctic, sea ice accumulates in the fall and winter and diminishes in the spring and summer, though it does not vanish entirely.

### Why is Sea Ice Important?

Sea ice plays profound roles in polar ecosystems, environment, climate and weather.Sea ice is crucial in polar ecosystems, environmental balance and climate, and weather patterns.


### More Info on Sea Ice

-   [Sea Ice on NOAA/NESDIS](https://www.nesdis.noaa.gov/our-environment/ice-snow/sea-ice)
-   [SeaIce on NASA Earth Observatory](https://earthobservatory.nasa.gov/features/SeaIce)
-   [Quick Facts about Sea Ice from NSIDC](https://nsidc.org/learn/parts-cryosphere/sea-ice/quick-facts-about-sea-ice)
-   [Sea Ice Data Catalog (NOAA PolarWatch)](https://polarwatch.noaa.gov/)
-   [Tutorial and code for Satellite data](https://polarwatch.noaa.gov/tools-training/code-gallery/)

