name: Update daily data

on:
  schedule:
    # Runs at 04:00 UTC every day
    # '0 4 * * *', '*/10 * * * *'
    - cron: '0 4 * * *'
jobs:
  update-daily-data:
    name: Run Python to update data
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: seaice
          environment-file: scripts/environment.yaml
          python-version: 3.9
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Install Dask
        run: conda install -c conda-forge dask
      - name: Run Python script
        run: |
            python scripts/update_daily_extent.py  # This script updates CSV files in data/
      - name: Commit and push if changes
        run: |
          git config --global user.email "sun.bak-hospital@noaa.gov"
          git config --global user.name "Sunny Hospital"
          git pull origin main
          git add data/*.csv
          git commit -m "Update CSV data" || echo "No changes to commit"
          git push


         
        
    
